language: c++
sudo: true

env:
  global:
  - LLVM_VERSION=3.9.0
  - TRAVIS_ENCRYPTION_LABEL="d0f036b99c7e"

matrix:
  include:
  - os: linux
    env: LLVM_ARCH="x86_64-linux-gnu-debian8"
  - os: osx
    env: LLVM_ARCH="x86_64-apple-darwin"
  allow_failures:
  - os: linux

addons:
  apt:
    packages:
    - libz-dev
    - libedit-dev
    - python-dev

before_install:
- mkdir -p "llvm-${LLVM_VERSION}"
- curl -s "http://releases.llvm.org/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-${LLVM_ARCH}.tar.xz" -o llvm.tar.xz
- tar -xf llvm.tar.xz --strip-components=1 -C "llvm-${LLVM_VERSION}"
- git clone --depth 5 "https://github.com/zneak/fcd-tests.git" tests

install:
-
  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    curl -Ls https://github.com/aquynh/capstone/archive/3.0.4.tar.gz -o capstone-3.0.4.tar.gz;
    tar -xf capstone-3.0.4.tar.gz;
    cd capstone-3.0.4;
    make -j3;
    sudo make install;
  else
    brew update;
    brew install capstone;
  fi

script:
- 
  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    rm -rf build && mkdir build && cd build;
    export LLVM_DIR="../llvm-${LLVM_VERSION}/lib/cmake/llvm";
    export Clang_DIR="../llvm-${LLVM_VERSION}/lib/cmake/clang";
    export CXX="../llvm-${LLVM_VERSION}/bin/clang++";
    cmake ..;
    make -j3;
    cd ..;
    export LD_LIBRARY_PATH="$(dirname $0)/llvm-${LLVM_VERSION}/lib";
    export FCD="build/fcd";
  else
    xcodebuild -target fcd -configuration Release \
      CAPSTONE_DIR=/usr/local/Cellar/capstone/3.0.4 \
      LLVM_BUILD_DIR="llvm-${LLVM_VERSION}";
    export FCD="build/Release/fcd";
  fi

- eval "${FCD}" --version
- tests/test.sh "${FCD}" "${TRAVIS_ENCRYPTION_LABEL}" "$(git rev-parse --verify HEAD)"
